# Generated by Django 3.2 on 2021-04-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', null=True, verbose_name='수정일')),
                ('content', models.TextField(max_length=200, verbose_name='내용')),
                ('images', models.ImageField(blank=True, null=True, upload_to='files')),
                ('like', models.IntegerField(blank=True, default=0, null=True, verbose_name='좋아요')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'db_table': 'posts_to',
            },
        ),
    ]
