# Generated by Django 3.2 on 2021-04-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요'),
        ),
    ]
