# Generated by Django 3.2 on 2021-04-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postmodel_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='like',
        ),
    ]
