# Generated by Django 3.2 on 2021-04-09 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postmodel_like_counted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='like_counted',
        ),
    ]
