# Generated by Django 3.2 on 2021-04-07 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성된 일자입니다.', verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정된 사용자입니다.', null=True, verbose_name='수정일')),
                ('review_content', models.CharField(max_length=120, verbose_name='댓글')),
                ('post_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_model', to='posts.postmodel')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'reviews_to',
            },
        ),
    ]
